// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknow(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOW.String() && e.Code == 500
}

func ErrorUnknow(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOW.String(), fmt.Sprintf(format, args...))
}

//账号密码错误
func IsAccountPwdError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AccountPwdError.String() && e.Code == 500
}

//账号密码错误
func ErrorAccountPwdError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AccountPwdError.String(), fmt.Sprintf(format, args...))
}

//验证码错误
func IsCaptchaError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CaptchaError.String() && e.Code == 500
}

//验证码错误
func ErrorCaptchaError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CaptchaError.String(), fmt.Sprintf(format, args...))
}
